backend:
  name: github
  repo: Mumchip/accessible-journeys-inc
  branch: main
  base_url: https://cms-oauth-ochre.vercel.app
  auth_endpoint: /api/auth
  site_id: https://www.kidschoicenj.com

media_folder: "public/uploads"
public_folder: "/uploads"


collections:
  - name: "site"
    label: "Site Text"
    files:
      - file: "content/text.json"
        label: "Home Page Text"
        name: "home"
        fields:
          - { name: "hero_title", label: "Hero Title", widget: "string" }
          - { name: "hero_subtitle", label: "Hero Subtitle", widget: "string" }

