backend:
  name: github
  repo: Mumchip/accessible-journeys-inc
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Text"
    files:
      - file: "content/text.json"
        label: "Home Page Text"
        name: "home"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "text"}
